### ISSUE TITLE
 Exception setting "OutputEncoding"

### ISSUE THREAD

**Issue by wendefeuer** [admins-little-helper/DeeplTranslate#2]
Version: 1.4.1

When I run "Invoke-DeeplTranslateText" in the Powershell 7 console everything is ok.
However, when I use the command in Powershell Studio 2024 with PS7, I get the following error message:
-----------------------------------------------------------------------------
Invoke-DeeplTranslateText.ps1 (254): ERROR: At Line: 254
ERROR: |
ERROR: 254 | [Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
ERROR: | ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ERROR: | Exception setting "OutputEncoding": "The handle is invalid."
-----------------------------------------------------------------------------

I have commented out line 254 in the Invoke-DeeplTranslateText.ps1 file. Then the error is gone and the application runs properly

**Comment by admins-little-helper** [comment]
Thanks for the hint.
This line actually was a leftover from testing on PowerShell 5.1. But since the module's minimum required PowerShell Version is set to 7.0 due to some other dependencies.

It has been removed now and the module version has been updated to 1.4.2.
